// GENERATED by scripts/food-drawings.mjs. Do not edit by hand.
/** Foods shown as a colour drawing (no honest photo exists), with the ones whose card says "None at all". */
export const DRAWN_FOODS: readonly string[] = [];
export const DRAWN_SKIP: readonly string[] = [];
