// Add genuinely-new, high-confidence foods from a submitted list. Database only:
// no rule/engine changes. Items already on the site, pure cooking-variants of
// existing foods, raw grains/flours, and anything whose safety sign is not
// 100% certain were deliberately left out. Verdicts match existing analogous
// foods (rice=yellow, sauces=green, offal/fish=green, sweets=red, ...).
// Every field is specific and follows the house rules.
import { readFileSync, writeFileSync } from "node:fs";

const FILE = "data/foods.json";
const foods = JSON.parse(readFileSync(FILE, "utf8"));

const add = [
  // --- rice / starch ---
  { id: "parboiled-rice", name: "Parboiled Rice (local rice)", aliases: ["parboiled rice", "local rice"], category: "rice", role: "starch", carbLoad: "high", gi: "medium", baseVerdict: "yellow", portionGuidance: "Half a cup, cooked (about 130g).", pairingAdvice: "Add a vegetable stew and fish, chicken, or meat.", frequency: "About 3 times a week.", logicNote: "Parboiled rice raises sugar a little slower than white rice, but it is still a starch. Keep the portion small.", tags: [] },
  { id: "baguette", name: "Baguette (French bread)", aliases: ["baguette", "french bread"], category: "bread", role: "starch", carbLoad: "high", gi: "high", baseVerdict: "red", portionGuidance: "Avoid. If you do have it, only one short piece (about 30g), never on its own.", pairingAdvice: "Add an egg and vegetables, never bread on its own.", frequency: "Rarely; a treat.", logicNote: "White refined flour, like agege bread; one of the fastest spikes.", tags: [] },
  { id: "cocoyam-fufu", name: "Cocoyam Fufu", aliases: ["cocoyam fufu", "ede fufu"], category: "swallow", role: "starch", carbLoad: "medium", gi: "medium", baseVerdict: "yellow", portionGuidance: "One ball the size of your fist. That is about half a cup (100g).", pairingAdvice: "A green vegetable soup, like efo riro or okra, plus fish or meat.", frequency: "About 3 times a week.", logicNote: "A soft cocoyam swallow. More fibre than eba, but still a starch, so keep the ball small.", tags: [] },
  { id: "sweet-potato-porridge", name: "Sweet Potato Porridge", aliases: ["sweet potato porridge", "sweet potato pottage"], category: "tuber", role: "starch", carbLoad: "medium", gi: "medium", baseVerdict: "yellow", portionGuidance: "One small bowl. That is about three-quarters of a cup (150g).", pairingAdvice: "Add plenty of vegetables and fish or meat.", frequency: "About 2 times a week.", logicNote: "Sweet potato is gentler than yam, but the porridge is still a starch. Load the vegetables and keep the portion small.", tags: [] },
  // --- sauces / stews (low-carb, so friendly for sugar) ---
  { id: "tomato-stew", name: "Tomato Stew (obe ata)", aliases: ["tomato stew", "obe ata", "stew", "fish stew", "chicken stew", "beef stew", "assorted meat stew"], category: "soup", role: "soup", carbLoad: "low", gi: "low", baseVerdict: "green", portionGuidance: "Two to three serving spoons (about half a cup).", pairingAdvice: "It already has fish, chicken, or meat. Eat with a small portion of rice (half a cup, 130g) or a fist-size ball of swallow (100g).", frequency: "You can eat this every day.", logicNote: "A pepper and tomato sauce with oil and protein. It is low in carbs, so it does not raise sugar much on its own; the rice or swallow is what to watch.", tags: [] },
  { id: "ayamase", name: "Ofada Sauce (Ayamase)", aliases: ["ayamase", "ofada sauce", "designer stew"], category: "soup", role: "soup", carbLoad: "low", gi: "low", baseVerdict: "green", portionGuidance: "Two to three serving spoons (about half a cup).", pairingAdvice: "It already has assorted meat. Eat with a small portion of ofada rice (half a cup, 130g).", frequency: "About 3 times a week.", logicNote: "A green pepper sauce with plenty of palm oil and assorted meat. Low in carbs, but heavy on oil, so keep the oil in check.", tags: [] },
  { id: "garden-egg-sauce", name: "Garden Egg Sauce", aliases: ["garden egg sauce"], category: "soup", role: "soup", carbLoad: "low", gi: "low", baseVerdict: "green", portionGuidance: "Two to three serving spoons (about half a cup).", pairingAdvice: "Eat with a fist-size piece of boiled yam (100g) or two slices of plantain (80g), plus fish or meat.", frequency: "You can eat this every day.", logicNote: "Made from garden eggs, pepper, and oil. Low in carbs and friendly for sugar.", tags: [] },
  { id: "pepper-sauce", name: "Pepper Sauce (ata dindin)", aliases: ["pepper sauce", "ata dindin", "fried pepper sauce"], category: "soup", role: "soup", carbLoad: "low", gi: "low", baseVerdict: "green", portionGuidance: "One to two serving spoons (about a quarter cup).", pairingAdvice: "Use with a small portion of rice, yam, or plantain, plus fish or meat.", frequency: "You can eat this every day.", logicNote: "Fried pepper, onion, and oil. Very low in carbs; the starch it goes with is what to watch.", tags: [] },
  // --- proteins (offal and fish; low-carb) ---
  { id: "cow-leg", name: "Cow Leg", aliases: ["cow leg", "cow foot"], category: "protein", role: "protein", carbLoad: "low", gi: "low", baseVerdict: "green", portionGuidance: "One to two pieces (about 90g).", pairingAdvice: "In pepper soup or stew, with vegetables.", frequency: "About 4 times a week.", logicNote: "Mostly skin, bone, and collagen; low in carbs and does not raise sugar.", tags: [] },
  { id: "cow-tail", name: "Cow Tail", aliases: ["cow tail"], category: "protein", role: "protein", carbLoad: "low", gi: "low", baseVerdict: "green", portionGuidance: "One to two pieces (about 90g).", pairingAdvice: "In pepper soup or stew, with vegetables.", frequency: "About 4 times a week.", logicNote: "A fatty, low-carb meat that does not raise sugar. Trim heavy fat if you can.", tags: [] },
  { id: "smoked-fish", name: "Smoked Fish", aliases: ["smoked fish", "dry fish", "dried fish"], category: "protein", role: "protein", carbLoad: "low", gi: "low", baseVerdict: "green", portionGuidance: "One palm-size piece (about 90g).", pairingAdvice: "In soups, stews, and pepper sauce, with vegetables.", frequency: "You can eat this every day.", logicNote: "Dried, smoked fish; low in carbs and rich in protein. Rinse off extra salt.", tags: [] },
  // --- legumes ---
  { id: "african-yam-bean", name: "African Yam Bean", aliases: ["african yam bean", "yam bean", "azama"], category: "legume", role: "legume", carbLoad: "medium", gi: "low", baseVerdict: "green", portionGuidance: "Half a cup, cooked (about 130g).", pairingAdvice: "Fish, an egg, or two slices of plantain (80g).", frequency: "About 4 times a week.", logicNote: "A legume with plenty of fibre and protein, so the sugar rises slowly.", tags: [] },
  { id: "baked-beans", name: "Baked Beans (canned)", aliases: ["baked beans", "canned beans", "tinned beans"], category: "legume", role: "legume", carbLoad: "medium", gi: "medium", baseVerdict: "yellow", portionGuidance: "Half a cup (about 130g).", pairingAdvice: "Add an egg and vegetables. Eat with a small starch, not a large one.", frequency: "About 2 times a week.", logicNote: "Beans are friendly, but the tinned tomato sauce has added sugar, so keep the portion small.", tags: ["processed"] },
  // --- vegetables ---
  { id: "spring-onion", name: "Spring Onion", aliases: ["spring onion", "green onion", "scallion"], category: "vegetable", role: "vegetable", carbLoad: "low", gi: "low", baseVerdict: "green", portionGuidance: "A small handful, chopped (about 30g).", pairingAdvice: "Add to stews, sauces, salads, and stir-fries.", frequency: "You can eat this every day.", logicNote: "A flavour vegetable with almost no sugar.", tags: [] },
  { id: "celery", name: "Celery", aliases: ["celery"], category: "vegetable", role: "vegetable", carbLoad: "low", gi: "low", baseVerdict: "green", portionGuidance: "One to two stalks.", pairingAdvice: "In salads, soups, and stir-fries with protein.", frequency: "You can eat this every day.", logicNote: "Mostly water and fibre, with almost no sugar.", tags: [] },
  { id: "parsley", name: "Parsley", aliases: ["parsley"], category: "vegetable", role: "vegetable", carbLoad: "low", gi: "low", baseVerdict: "green", portionGuidance: "A small handful, chopped (about 20g).", pairingAdvice: "Sprinkle into sauces, salads, and soups.", frequency: "You can eat this every day.", logicNote: "A green herb with no real effect on sugar.", tags: [] },
  // --- salads ---
  { id: "nigerian-salad", name: "Nigerian Salad", aliases: ["nigerian salad"], category: "vegetable", role: "vegetable", carbLoad: "low", gi: "low", baseVerdict: "green", portionGuidance: "One plate of mostly vegetables (about one and a half cups).", pairingAdvice: "Add a boiled egg, chicken, or fish. Go easy on the salad cream, sweet corn, and baked beans.", frequency: "About 4 times a week.", logicNote: "Cabbage, lettuce, cucumber, and carrot are friendly. The salad cream, sweet corn, and baked beans add the sugar and fat, so go light on those.", tags: [] },
  { id: "tuna-salad", name: "Tuna Salad", aliases: ["tuna salad"], category: "protein", role: "protein", carbLoad: "low", gi: "low", baseVerdict: "green", portionGuidance: "One bowl (about one cup).", pairingAdvice: "Cucumber, lettuce, and tomato. Go easy on the mayonnaise.", frequency: "About 4 times a week.", logicNote: "Tuna and vegetables are low in carbs and high in protein. The mayonnaise is the only thing to keep small.", tags: [] },
  { id: "fruit-salad", name: "Fruit Salad", aliases: ["fruit salad"], category: "fruit", role: "fruit", carbLoad: "medium", gi: "medium", baseVerdict: "yellow", portionGuidance: "Half a cup of mixed fruit (about 80g).", pairingAdvice: "About 10 nuts, or a small cup of plain yogurt (150g). No sugar or cream.", frequency: "About 2 times a week.", logicNote: "A bowl of mixed fruit puts a lot of natural sugar together, so keep the portion small and add no sugar.", tags: [] },
  // --- fats / nuts / seeds / spices ---
  { id: "sesame-seed", name: "Sesame Seed (beniseed)", aliases: ["sesame", "sesame seed", "beniseed", "benniseed"], category: "nut", role: "fat", carbLoad: "low", gi: "low", baseVerdict: "green", portionGuidance: "One tablespoon (about 10g).", pairingAdvice: "Sprinkle on salads, vegetables, and soups.", frequency: "You can eat this every day.", logicNote: "Seeds with healthy fat and fibre, and very little sugar.", tags: [] },
  { id: "mixed-nuts", name: "Mixed Nuts", aliases: ["mixed nuts", "assorted nuts"], category: "nut", role: "fat", carbLoad: "low", gi: "low", baseVerdict: "green", portionGuidance: "A small handful, about 10 nuts (30g).", pairingAdvice: "Eat as a snack, or add to salads and plain yogurt.", frequency: "You can eat this every day.", logicNote: "Assorted nuts give healthy fat, protein, and fibre, with little sugar. Choose the unsalted, unsweetened kind.", tags: [] },
  { id: "peanut-butter", name: "Peanut Butter (no added sugar)", aliases: ["peanut butter", "groundnut paste", "groundnut butter"], category: "nut", role: "fat", carbLoad: "low", gi: "low", baseVerdict: "green", portionGuidance: "One tablespoon (about 15g).", pairingAdvice: "On one thin slice of bread (30g), or with celery.", frequency: "You can eat this every day.", logicNote: "Ground groundnuts give healthy fat and protein. Check the label and choose the kind with no added sugar.", tags: [] },
  { id: "curry-powder", name: "Curry Powder", aliases: ["curry", "curry powder"], category: "condiment", role: "condiment", carbLoad: "low", gi: "low", baseVerdict: "green", portionGuidance: "A pinch, for taste in cooking.", pairingAdvice: "Use in rice, stews, and sauces.", frequency: "You can eat this every day.", logicNote: "A spice blend for flavour, with no effect on sugar.", tags: [] },
  { id: "thyme", name: "Thyme", aliases: ["thyme"], category: "condiment", role: "condiment", carbLoad: "low", gi: "low", baseVerdict: "green", portionGuidance: "A pinch, for taste in cooking.", pairingAdvice: "Use in rice, stews, soups, and meat.", frequency: "You can eat this every day.", logicNote: "A herb for flavour, with no effect on sugar.", tags: [] },
  // --- sweets / spreads / sweet drinks (concentrated sugar) ---
  { id: "chocolate-bar", name: "Chocolate Bar", aliases: ["chocolate", "chocolate bar", "candy bar"], category: "snack", role: "starch", carbLoad: "high", gi: "high", baseVerdict: "red", portionGuidance: "Avoid. If you do have it, only two small squares.", pairingAdvice: "Better to snack on about 10 nuts.", frequency: "Rarely; a treat.", logicNote: "Milk chocolate is mostly sugar and fat, and raises sugar fast.", tags: [] },
  { id: "peanut-candy", name: "Peanut Candy (groundnut brittle)", aliases: ["peanut candy", "groundnut brittle", "groundnut candy"], category: "snack", role: "starch", carbLoad: "high", gi: "high", baseVerdict: "red", portionGuidance: "Avoid. If you do have it, only one small piece (about 30g).", pairingAdvice: "Better to snack on plain groundnuts, about 10.", frequency: "Rarely; a treat.", logicNote: "Groundnuts set in melted sugar; the groundnut is fine but the sugar is not.", tags: [] },
  { id: "baba-dudu", name: "Baba Dudu (caramel toffee)", aliases: ["baba dudu", "caramel toffee", "toffee"], category: "snack", role: "starch", carbLoad: "high", gi: "high", baseVerdict: "red", portionGuidance: "Avoid. If you do have it, only one small piece.", pairingAdvice: "Better to have a small piece of fruit instead.", frequency: "Rarely; a treat.", logicNote: "A hard toffee made from melted sugar; it raises sugar fast.", tags: [] },
  { id: "chocolate-spread", name: "Chocolate Spread", aliases: ["chocolate spread", "nutella"], category: "sugar", role: "starch", carbLoad: "high", gi: "high", baseVerdict: "red", portionGuidance: "Avoid. If at all, only a thin scrape on one slice of bread.", pairingAdvice: "Better to use one tablespoon of peanut butter with no added sugar.", frequency: "Rarely; a treat.", logicNote: "Mostly sugar and oil; it raises sugar fast.", tags: [] },
  { id: "jam", name: "Jam / Marmalade", aliases: ["jam", "marmalade", "fruit jam"], category: "sugar", role: "starch", carbLoad: "high", gi: "high", baseVerdict: "red", portionGuidance: "Avoid. If at all, only a thin scrape on one slice of bread.", pairingAdvice: "Better to top your bread with an egg or avocado.", frequency: "Rarely; a treat.", logicNote: "Fruit boiled with a lot of sugar; the fibre is gone and it raises sugar fast.", tags: [] },
  { id: "flavoured-milk", name: "Flavoured Milk (chocolate / strawberry)", aliases: ["flavoured milk", "flavored milk", "chocolate milk", "strawberry milk", "vanilla milk"], category: "drink", role: "drink", carbLoad: "high", gi: "high", baseVerdict: "red", portionGuidance: "Avoid. Choose plain unsweetened milk instead.", pairingAdvice: "Nothing makes a sweet milk drink safe. Drink plain milk or water.", frequency: "Rarely; a treat.", logicNote: "Chocolate and strawberry milk carry a lot of added sugar in liquid form, which spikes fast.", tags: ["processed"] },
];

const ids = new Set(foods.map((f) => f.id));
for (const f of add) {
  if (ids.has(f.id)) {
    console.error("duplicate id", f.id);
    process.exit(1);
  }
  ids.add(f.id);
}

const out = [...foods, ...add];
writeFileSync(FILE, JSON.stringify(out, null, 2) + "\n");
console.log(`added ${add.length}. total: ${out.length}`);
